#!/usr/bin/env python3
"""ela map deps — what the app layer calls, derived from the code, not from a document.

The owning team's registry (code/web/mediahub-agent/workspace.json `callGraph`) records only the
five services in its own release scope plus four named out-of-scope Java services. Everything the
app layer calls *outside* that scope — the platform services other teams own — is invisible there
by design. That remainder is what this artefact carries, and it is the half Evan needs: routing a
bug to the team that owns the service, and knowing a promotion's blast radius past the bundle.

Facts come from a git ref, never from the working tree: an edge is only as true as the commit it
was read at, so every scan stamps the sha it read. `check` re-resolves those refs and tells you
which repos moved — staleness is a `git rev-parse`, not a date someone has to remember.

Curated fields (`services:` — role, owner, repo) survive a rescan; `edges:` is regenerated whole.
"""
import argparse, json, os, re, subprocess, sys

HEADER = """\
# What the MediaHub app layer calls. GENERATED by ela `skills/map/deps.py scan --write`.
# Curated blocks — `scope:`, `name_resolution:`, `services:` — round-trip and survive a rescan.
# `repos:` and `edges:` are regenerated whole; do not hand-edit them, the next scan wins.
#
# WHY THIS EXISTS BESIDE THE OWNING TEAM'S REGISTRY
#   code/web/mediahub-agent/workspace.json holds a `callGraph` the web team maintains, and inside its
#   own charter it is authoritative: the five services in that repo's release scope plus four named
#   out-of-scope Java services. It records nothing outside that, by design — which is why tvucc-media
#   reads there as `callees: []` while its code calls ten platform services. THIS FILE CARRIES THAT
#   REMAINDER: the platform layer other teams own, which is what decides who a bug is routed to and
#   how far a promotion reaches past the bundle. `deps.py reconcile` keeps the two apart and reports
#   an edge their charter should cover but misses. Disagreement is a finding, never a silent merge.
#
# NAMES
#   An edge is keyed by the EUREKA service name, which is not the repo name, not the GM service name
#   and not a Helm slug — services.yaml keeps those apart and so does this file. tvucc-media
#   registers as `media-mx`. Where `@FeignClient` names a property with no default, only the config
#   server knows the value: `name_resolution:` resolves it ONLY with first-hand evidence, and an
#   unverified one stays `name: null` rather than being guessed.
#
# STALENESS IS MECHANICAL
#   Every repo records the commit its edges were read at. `deps.py check --fetch` re-resolves the ref
#   and says which repos moved, so "is this still true" is a git question, not a date to remember.
#
# THREE BLIND SPOTS, ALL REAL
#   1. `${key:default}` defaults are NOT what runs. Real addresses come from Spring Cloud Config per
#      profile. This file says which service is called, never which host an environment reaches.
#   2. Event edges are invisible to a @FeignClient scan. `event_subscriptions.declared` parses the
#      RabbitMQ groups in application.yml; Java-side bindings are only pointed at
#      (`listener_files_to_read`) because there is one in the whole app layer and a regex fitted to a
#      single sample would be a liability.
#   3. A frontend's real dependencies arrive at run time from the backend's initConfig, so only the
#      dev-server proxy table and the initConfig key names are derivable from source.
#
# `referenced_in_src: false` means the client is declared but has no call site at this ref — a claim
# to verify, not a verdict: it can also mean the contract is inherited or invoked reflectively.
"""

SITE = os.path.expanduser("~/.claude/ela/site.json")

def site():
    with open(SITE) as f:
        return json.load(f)

def git(path, *args, timeout=60):
    try:
        p = subprocess.run(["git", "-C", path, *args], capture_output=True, text=True, timeout=timeout)
        return p.stdout if p.returncode == 0 else ""
    except Exception:
        return ""

def blob(path, ref, f):
    return git(path, "show", f"{ref}:{f}")

def tree(path, ref, *globs):
    out = git(path, "ls-tree", "-r", "--name-only", ref)
    files = [x for x in out.splitlines() if x]
    if globs:
        files = [f for f in files if any(re.search(g, f) for g in globs)]
    return files


# ---- Java: @FeignClient -------------------------------------------------------------------------
# One annotation may span lines and carry name= / value= / url= / configuration= in any order.
FEIGN = re.compile(r"@FeignClient\s*\(")
PROP = re.compile(r"\$\{([A-Za-z0-9_.\-]+)(?::([^}]*))?\}")
MAPPING = re.compile(r"@(Get|Post|Put|Delete|Patch|Request)Mapping\s*\(([^)]*)\)", re.S)
METHOD = re.compile(r"^\s*(?:public\s+)?[\w<>\[\],.\s?]+\s+(\w+)\s*\(", re.M)
STR = re.compile(r'"([^"]*)"')

def balanced(text, start, open_ch="(", close_ch=")"):
    """Return the substring inside the bracket pair that opens at `start`."""
    depth, i = 0, start
    while i < len(text):
        if text[i] == open_ch:
            depth += 1
        elif text[i] == close_ch:
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i
        i += 1
    return "", start

def feign_target(args):
    """@FeignClient argument list -> (eureka name, pinned url or None, unresolved property or None)."""
    kv, unresolved = {}, None
    for key in ("name", "value", "url"):
        m = re.search(rf"\b{key}\s*=\s*(\"[^\"]*\"|[^,]+)", args)
        if m:
            s = STR.search(m.group(1))
            kv[key] = s.group(1) if s else m.group(1).strip()
    if "name" not in kv and "value" not in kv:          # single positional argument
        s = STR.search(args)
        if s:
            kv["value"] = s.group(1)
    raw = kv.get("name") or kv.get("value") or ""
    p = PROP.fullmatch(raw.strip())
    if p:
        if p.group(2):
            raw = p.group(2)                            # the default is the name that actually resolves
        else:
            unresolved, raw = p.group(1), p.group(1)    # no default — only the config server knows
    return raw, kv.get("url"), unresolved

def apply_resolution(edges, table):
    """Curated property -> Eureka name. Recorded with its evidence, never guessed silently."""
    for e in edges:
        r = table.get(e.get("unresolved_property"))
        if not r:
            continue
        if r.get("name"):
            e["to_property"], e["to"] = e["to"], r["name"]
            e["resolved_by"] = r.get("evidence", "map/dependencies.yaml name_resolution")
        else:
            # deliberately unresolved — the edge keeps the property as its key so it stays visibly
            # unanswered instead of quietly pointing at a plausible-looking service
            e["resolution_attempted"] = r.get("evidence", "")

def javadoc_before(text, idx):
    """First prose line of the javadoc block immediately above position idx."""
    head = text[:idx]
    m = list(re.finditer(r"/\*\*(.*?)\*/", head, re.S))
    if not m or head[m[-1].end():].strip().count("\n") > 3:
        return ""
    for line in m[-1].group(1).splitlines():
        line = line.strip().lstrip("*").strip()
        if line and not line.startswith("@") and not line.startswith("<"):
            return re.sub(r"</?[a-z]+>", "", line)[:120]
    return ""

def scan_java(path, ref):
    """-> list of edge dicts, one per @FeignClient interface."""
    edges = []
    files = tree(path, ref, r"^src/main/.*\.java$")
    texts = {}
    for f in files:
        t = blob(path, ref, f)
        if "@FeignClient" in t:
            texts[f] = t
    # every symbol referenced from src/main, to tell a live client from a dead one
    all_main = " ".join(blob(path, ref, f) for f in files) if len(files) < 4000 else ""
    for f, t in sorted(texts.items()):
        m = FEIGN.search(t)
        if not m:
            continue
        args, close = balanced(t, m.end() - 1)
        name, pinned, unresolved = feign_target(args)
        if not name:
            continue
        im = re.search(r"\b(?:public\s+)?interface\s+(\w+)(?:\s*<[^>]*>)?\s*(?:extends\s+([\w.,<>\s]+?))?\s*\{", t[close:])
        iface = im.group(1) if im else os.path.basename(f)[:-5]
        inherits = " ".join((im.group(2) or "").split()) if im else ""
        body = t[close:]
        calls = []
        for mm in MAPPING.finditer(body):
            s = STR.search(mm.group(2))
            fn = METHOD.search(body[mm.end():])
            calls.append({"http": mm.group(1).upper().replace("REQUEST", "ANY"),
                          "path": s.group(1) if s else "?",
                          "method": fn.group(1) if fn else "?"})
        used = all_main.count(iface) > 1 if all_main else None
        edges.append({"to": name, "client": iface, "file": f,
                      **({"inherits": inherits} if inherits else {}),
                      "purpose": javadoc_before(t, m.start()),
                      "endpoints": calls,
                      **({"pinned_url": pinned} if pinned else {}),
                      **({"unresolved_property": unresolved} if unresolved else {}),
                      **({"referenced_in_src": used} if used is not None else {})})
    return edges

def scan_value_urls(path, ref):
    """@Value keys whose name or default looks like an address — direct HTTP, no service discovery."""
    out = {}
    for f in tree(path, ref, r"^src/main/.*\.java$"):
        t = blob(path, ref, f)
        if "@Value" not in t:
            continue
        for m in re.finditer(r'@Value\s*\(\s*"\$\{([A-Za-z0-9_.\-]+)(?::([^"]*))?\}"', t):
            key, dflt = m.group(1), (m.group(2) or "")
            if not re.search(r"url|uri|host|endpoint|addr", key, re.I) and not dflt.startswith("http"):
                continue
            if dflt.startswith("{") or dflt.startswith('\\"'):   # a JSON blob, not an address
                continue
            out.setdefault(key, {"key": key, "default": dflt, "files": []})
            if f not in out[key]["files"]:
                out[key]["files"].append(f)
    return sorted(out.values(), key=lambda x: x["key"])

def scan_events(path, ref):
    """RabbitMQ event subscriptions — a dependency that no @FeignClient grep can see."""
    subs = []
    for f in tree(path, ref, r"^src/main/resources/.*\.(yml|yaml)$"):
        t = blob(path, ref, f)
        if "event_groups" not in t:
            continue
        cur = None
        for line in t.splitlines():
            s = re.match(r"\s*service:\s*(\S+)", line)
            if s:
                cur = {"publisher": s.group(1), "events": [], "file": f}
                subs.append(cur)
            e = re.match(r"\s*-\s+([a-z][a-z0-9.]+\.[a-z0-9.]+)\s*$", line)
            if e and cur is not None:
                cur["events"].append(e.group(1))
    # Only application.yml declarations are parsed. Bindings written in Java config (@RabbitListener)
    # are pointed at, not parsed: there is one in the whole app layer and a regex fitted to a single
    # sample would be a liability. Read the file.
    listeners = [f for f in tree(path, ref, r"^src/main/.*\.java$")
                 if "@RabbitListener" in blob(path, ref, f)]
    out = [s for s in subs if s["events"]]
    return {"declared": out, "listener_files_to_read": listeners} if (out or listeners) else {}

def scan_front(path, ref):
    """A frontend's two dependency surfaces, both derivable from source.

    dev_proxy: the dev-server table — prefix -> target expression. Targets are usually a variable
    into a per-environment map, so the expression is kept verbatim rather than resolved.
    init_config: keys the UI reads off the backend's initConfig response. These are the *runtime*
    dependencies — the browser calls those addresses directly — and the values only exist at run
    time, so the key and its call-site count are as far as source goes.
    """
    proxy, init = [], {}
    for f in tree(path, ref, r"^(vue|vite)\.config\.[jt]s$"):
        t = blob(path, ref, f)
        m = re.search(r"\bproxy\s*:\s*\{", t)
        if not m:
            continue
        body, _ = balanced(t, m.end() - 1, "{", "}")
        # a proxy entry is a '/prefix' key; its target is the next `target:` before the following key
        keys = [(mm.start(), mm.group(1)) for mm in re.finditer(r"'(/[^']*)'\s*:", body)]
        for i, (pos, prefix) in enumerate(keys):
            end = keys[i + 1][0] if i + 1 < len(keys) else len(body)
            seg = body[pos:end]
            tg = re.search(r"target\s*:\s*([^,\n]+)", seg)
            fn = re.search(r":\s*(\w+)\(\)", seg)
            proxy.append({"prefix": prefix,
                          "target": (tg.group(1) if tg else (fn.group(1) + "()" if fn else "?")).strip(),
                          "ws": bool(re.search(r"\bws\s*:\s*true", seg))})
    for f in tree(path, ref, r"^src/.*\.(js|ts|vue)$"):
        for k in re.findall(r"initConfig\.([A-Za-z][A-Za-z0-9]*)", blob(path, ref, f)):
            init[k] = init.get(k, 0) + 1
    return {"dev_proxy": proxy,
            "init_config_keys": [{"key": k, "uses": n} for k, n in
                                 sorted(init.items(), key=lambda x: -x[1])]}


# ---- artefact -----------------------------------------------------------------------------------
def load(p):
    import yaml
    with open(p) as f:
        return yaml.safe_load(f) or {}

def resolve_ref(path, ref):
    sha = git(path, "rev-parse", "--short", ref).strip()
    when = git(path, "log", "-1", "--format=%ad", "--date=short", ref).strip()
    return sha, when

def cmd_scan(a):
    doc = load(a.file)
    code = site()["code"]
    scope = doc.get("scope") or {}
    edges, repos = {}, {}
    for repo, spec in scope.items():
        path = os.path.join(code, repo)
        ref, kind = spec["ref"], spec.get("kind", "java")
        if not os.path.isdir(path):
            repos[repo] = {"ref": ref, "error": "not on disk"}
            continue
        if a.fetch:
            git(path, "fetch", "--quiet", "--all", timeout=180)
        sha, when = resolve_ref(path, ref)
        if not sha:
            repos[repo] = {"ref": ref, "error": f"ref {ref} does not resolve"}
            continue
        repos[repo] = {"ref": ref, "commit": sha, "commit_date": when}
        if kind == "java":
            fe = scan_java(path, ref)
            apply_resolution(fe, doc.get("name_resolution") or {})
            edges[repo] = {"feign": fe,
                           "direct_urls": scan_value_urls(path, ref),
                           "event_subscriptions": scan_events(path, ref)}
        else:
            edges[repo] = scan_front(path, ref)
    doc["repos"], doc["edges"] = repos, edges          # regenerated whole
    doc.setdefault("services", {})                     # curated, preserved
    doc["services"] = {k: v for k, v in doc["services"].items() if k}   # never key a service on nothing
    for repo in edges:
        for e in edges[repo].get("feign", []):
            if e.get("to"):
                doc["services"].setdefault(e["to"], {"role": None, "owner": None, "repo": None})
    # an auto-added stub whose edge is gone (e.g. a property later resolved to its real name) is
    # dropped; a curated entry is never dropped just because this scan saw no edge for it
    live = {e.get("to") for r in edges.values() for e in r.get("feign", [])}
    doc["services"] = {k: v for k, v in doc["services"].items() if k in live or v.get("role")}
    doc["services"] = dict(sorted(doc["services"].items(), key=lambda kv: str(kv[0]).lower()))
    if a.write:
        import yaml
        with open(a.file, "w") as f:
            f.write(HEADER)                            # prose the dumper would otherwise drop
            yaml.safe_dump(doc, f, allow_unicode=True, sort_keys=False, width=120)
        print(f"wrote {a.file}")
    counts = {r: len(v.get("feign", v.get("dev_proxy", []))) for r, v in edges.items()}
    for r, n in counts.items():
        print(f"{r:<28} {repos[r].get('commit','—'):>9}  {repos[r]['ref']:<34} {n:>3} edges")

def cmd_check(a):
    """Is the artefact still true? Compare the recorded sha against the ref today."""
    doc, code, stale = load(a.file), site()["code"], 0
    for repo, rec in (doc.get("repos") or {}).items():
        path = os.path.join(code, repo)
        if a.fetch:
            git(path, "fetch", "--quiet", "--all", timeout=180)
        now, _ = resolve_ref(path, rec.get("ref", ""))
        ok = now and now == rec.get("commit")
        stale += 0 if ok else 1
        print(f"{'ok ' if ok else 'STALE'} {repo:<28} recorded {rec.get('commit','—')}  now {now or '—'}")
    print(f"\n{stale} repo(s) moved since the last scan." if stale else "\nartefact matches every ref.")
    return 1 if stale else 0

def cmd_reconcile(a):
    """Derived edges vs. the owning team's callGraph. Disagreement is a finding, not a merge.

    workspace.json is authoritative inside its own charter (five in-scope services plus four named
    out-of-scope ones) and silent outside it. So there are two verdicts worth separating: an edge it
    should carry but does not (report to the web team), and an edge outside its charter (this file's
    reason to exist).
    """
    doc = load(a.file)
    ws = os.path.join(site()["code"], "web/mediahub-agent/workspace.json")
    if not os.path.isfile(ws):
        print(f"owner registry not on disk: {ws}"); return 1
    with open(ws) as f:
        reg = json.load(f)
    cg = {k: v for k, v in reg["callGraph"].items() if k != "_comment"}
    in_scope = set(cg)
    named_ext = {n for v in cg.values() for n in v.get("externalCallees", []) + v.get("externalCallers", [])}
    known = in_scope | named_ext
    alias = {v.get("eureka", k): k for k, v in (doc.get("services") or {}).items() if v.get("eureka")}
    alias.update({"media-mx": "tvucc-media", "ORCHESTRATION": "orchestration"})
    gaps, outside = [], []
    for repo, e in (doc.get("edges") or {}).items():
        name = repo.split("/")[-1]
        if name not in cg:
            continue
        recorded = {alias.get(x, x) for x in cg[name].get("callees", []) + cg[name].get("externalCallees", [])}
        for x in e.get("feign", []):
            to = alias.get(x["to"], x["to"])
            if to in recorded or to == name:
                continue
            (gaps if to in known else outside).append((name, to, x["client"], len(x["endpoints"])))
    print("A. inside the registry's charter but MISSING from it — report to the owning team:")
    for n, to, c, k in sorted(gaps) or [("", "(none)", "", 0)]:
        print(f"   {n:<18} -> {to:<26} {c} ({k} endpoints)" if n else "   (none)")
    print(f"\nB. outside its charter — the platform layer, which is why this file exists ({len(outside)} edges):")
    seen = {}
    for n, to, c, k in outside:
        seen.setdefault(to, []).append(n)
    for to in sorted(seen):
        svc = (doc.get("services") or {}).get(to) or {}
        print(f"   {to:<26} <- {', '.join(sorted(set(seen[to]))):<44} {svc.get('owner') or 'owner?'}")
    return 0

def _matches(q, repo, x):
    """A query hits an edge by either side or by what is called on it: an error message names an
    endpoint far more often than it names a service, and the endpoint is what locates the call site."""
    if not q:
        return True
    if q in x["to"].lower() or q in repo.lower():
        return True
    return any(q in (c.get("path") or "").lower() or q in (c.get("method") or "").lower()
               for c in x.get("endpoints") or [])


def cmd_show(a):
    doc = load(a.file)
    q = (a.what or "").lower()
    for repo, e in (doc.get("edges") or {}).items():
        for x in e.get("feign", []):
            if not _matches(q, repo, x):
                continue
            svc = (doc.get("services") or {}).get(x["to"]) or {}
            print(f"\n{repo}  ->  {x['to']}   [{svc.get('owner') or 'owner?'}]  {svc.get('role') or ''}")
            print(f"  {x['file']}")
            if x.get("purpose"):
                print(f"  {x['purpose']}")
            for c in x["endpoints"][:a.limit]:
                print(f"    {c['http']:<5} {c['path']:<46} {c['method']}")
            if len(x["endpoints"]) > a.limit:
                print(f"    … {len(x['endpoints']) - a.limit} more")

def cmd_callers(a):
    """The reverse edge: who calls this service, and for what. A change or an outage in a platform
    service breaks its callers, and this is the only place that list is derived from code rather
    than from a charter — 49 of the 59 edges fall outside the web team's own callGraph."""
    doc = load(a.file)
    q = a.service.lower()
    svc = (doc.get("services") or {}).get(a.service) or next(
        (v for k, v in (doc.get("services") or {}).items() if q in k.lower()), {})
    hits = []
    for repo, e in (doc.get("edges") or {}).items():
        for x in e.get("feign", []):
            if q in x["to"].lower():
                hits.append((repo, x))
    if a.json:
        print(json.dumps({"service": a.service, "owner": svc.get("owner") or "", "role": svc.get("role") or "",
                          "callers": [{"repo": r, "to": x["to"], "file": x["file"], "purpose": x.get("purpose") or "",
                                       "endpoints": x["endpoints"]} for r, x in hits],
                          "stamp": doc.get("stamp") or {}}, ensure_ascii=False)); return
    if not hits:
        print(f"no derived caller of {a.service!r}. That is not proof of none: the scan covers "
              f"the app-layer repos in scope (deps.py scan), so a caller outside them would not appear.",
              file=sys.stderr)
        sys.exit(3)
    print(f"# {a.service}   [{svc.get('owner') or 'owner?'}]  {svc.get('role') or ''}")
    print(f"# {len(hits)} caller(s) derived from code — the blast radius of a change here")
    print()
    for repo, x in hits:
        print(f"{repo}  ->  {x['to']}")
        print(f"  {x['file']}")
        if x.get("purpose"):
            print(f"  {x['purpose']}")
        for c in x["endpoints"][:a.limit]:
            print(f"    {c['http']:<5} {c['path']:<46} {c['method']}")
        if len(x["endpoints"]) > a.limit:
            print(f"    … {len(x['endpoints']) - a.limit} more")
        print()


# ---- render -------------------------------------------------------------------------------------
def _nid(s):
    return "n" + re.sub(r"[^A-Za-z0-9]", "_", s)


def cmd_render(a):
    """A mermaid projection of this artefact at the commits its edges were read at.

    The picture is GENERATED, never kept by hand (decision
    `2026-09-07-derived-facts-are-generated-knowledge-carries-the-reading`): a diagram maintained
    beside the code is wrong for every window between an edge landing and someone redrawing it and
    says nothing about being wrong. So this verb draws only what the artefact holds, stamps every
    repo's ref and commit into the output, and states inside the picture what the scan cannot see.
    What a reviewer adds is the reading — which edge is load-bearing, which seam should not exist —
    and that belongs in prose beside the render, never inside it.

    **One service is one node.** A callee whose `services:` entry names a repo in `scope:` is the
    same node as that repo (`tvucc-media` registers as `media-mx`, `orchestration` as
    `ORCHESTRATION`). Drawing the Eureka name apart from the repo would split the app layer in two
    and hide every cycle inside it — which is the first thing a review of this layer must see.

    Structure worth seeing, and how it is drawn:
      a client with no call site at this ref -> dashed edge (a claim to verify, not a verdict)
      a client pinned to a fixed URL         -> `url` on the edge and the node; it bypasses Eureka
      a callee that is an in-scope repo      -> an edge inside the app layer; a cycle shows as one
      an unresolved @FeignClient property    -> `?<property>`, a real edge to an unknown callee
      the owner of each callee               -> a subgraph; `owner unknown` is the load-bearing one
    """
    doc = load(a.file)
    services = doc.get("services") or {}
    edges = doc.get("edges") or {}
    repos = doc.get("repos") or {}
    scope = doc.get("scope") or {}
    unresolved = {p for p, r in (doc.get("name_resolution") or {}).items() if not (r or {}).get("name")}
    q = (a.focus or "").lower()

    # a callee that is one of our own repos collapses onto that repo's node
    home = {name: svc["repo"] for name, svc in services.items()
            if (svc or {}).get("repo") in scope}

    inscope, external, links = [], {}, []
    for repo, e in edges.items():
        rows = [x for x in e.get("feign", [])
                if not q or q in repo.lower() or q in x["to"].lower()]
        if not rows:
            continue
        if repo not in inscope:
            inscope.append(repo)
        for x in rows:
            to = home.get(x["to"], x["to"])
            if to in scope:
                if to not in inscope:
                    inscope.append(to)
            else:
                external.setdefault(to, services.get(to) or {})
            links.append((repo, to, len(x.get("endpoints") or []),
                          x.get("referenced_in_src") is False, bool(x.get("pinned_url"))))

    if not links:
        print(f"nothing to draw for {a.focus!r}: no feign edge matches it. `deps.py show` lists them.",
              file=sys.stderr)
        sys.exit(3)

    agg = {}
    for repo, to, n, unref, pinned in links:
        cur = agg.get((repo, to)) or [0, True, False]
        agg[(repo, to)] = [cur[0] + n, cur[1] and unref, cur[2] or pinned]

    def label(name):
        if name in scope:
            short = name.split("/")[-1]
            eureka = next((s for s, r in home.items() if r == name and s.lower() != short.lower()), None)
            return f"{short} ({eureka})" if eureka else short
        tag = "  url" if (external.get(name) or {}).get("pinned_url") else ""
        return f"?{name}  unresolved" if name in unresolved else f"{name}{tag}"

    out = ["%% GENERATED by ela `deps.py render`. Regenerate it; never edit it.",
           "%% @FeignClient edges derived from source at these refs:"]
    for repo in inscope:
        r = repos.get(repo) or {}
        out.append(f"%%   {repo:<28} {r.get('ref', '?'):<32} {r.get('commit', '?')}  {r.get('commit_date', '?')}")
    out += ["%% Absent by construction: config-server addresses (an edge names the service, never the host),",
            "%% event bindings written in Java config, a frontend's run-time initConfig dependencies."]
    out += ["", f"flowchart {a.direction}", '  subgraph app["app layer — repos in scope"]']
    for repo in inscope:
        out.append(f'    {_nid(repo)}["{label(repo)}"]')
    out.append("  end")

    groups = {}
    for to, svc in external.items():
        groups.setdefault((svc or {}).get("owner") or "owner unknown", []).append(to)
    for i, (owner, members) in enumerate(sorted(groups.items(),
                                                key=lambda kv: (kv[0] == "owner unknown", kv[0]))):
        out.append(f'  subgraph g{i}["{owner}"]')
        for to in sorted(members):
            out.append(f'    {_nid(to)}["{label(to)}"]')
        out.append("  end")

    for (repo, to), (n, unref, pinned) in sorted(agg.items()):
        # n == 0: the client is declared but no endpoint was parsed from it — say that, do not print "0"
        lab = ("client only" if n == 0 else f"{n} ep" + ("" if n == 1 else "s")) + (" url" if pinned else "")
        out.append(f"  {_nid(repo)} " + (f"-. {lab} .->" if unref else f"-- {lab} -->") + f" {_nid(to)}")

    text = "\n".join(out) + "\n"
    internal = sum(1 for (r, t) in agg if t in scope)
    summary = (f"({len(inscope)} in scope, {len(external)} external, {len(agg)} edge(s), "
               f"{internal} of them inside the app layer)")
    if a.out:
        with open(a.out, "w") as f:
            f.write(text)
        print(f"{a.out}  {summary}")
    else:
        sys.stdout.write(text)
        print(f"%% {summary}")

def main():
    d = os.path.join(site().get("map_source") or site().get("map", ""), "dependencies.yaml")   # written to the source; reads go through the published copy
    ap = argparse.ArgumentParser(description="what the app layer calls — derived from the code at a ref")
    ap.add_argument("--file", default=d)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("scan", help="re-derive edges from the refs in scope:")
    p.add_argument("--write", action="store_true"); p.add_argument("--fetch", action="store_true")
    p = sub.add_parser("check", help="did any repo move since the scan?")
    p.add_argument("--fetch", action="store_true")
    sub.add_parser("reconcile", help="derived edges vs. code/web/mediahub-agent/workspace.json callGraph")
    p = sub.add_parser("show", help="edges, with what each one is called for; matches either side or an endpoint")
    p.add_argument("what", nargs="?"); p.add_argument("--limit", type=int, default=8)
    p = sub.add_parser("callers", help="who calls this service, and for what — the blast radius of a change")
    p.add_argument("service"); p.add_argument("--limit", type=int, default=8); p.add_argument("--json", action="store_true")
    p = sub.add_parser("render", help="the edges as a mermaid diagram, stamped with the commits they were read at")
    p.add_argument("--focus", help="only edges whose caller or callee matches this")
    p.add_argument("--direction", default="LR", choices=["LR", "TB"])
    p.add_argument("--out", help="write to this file instead of stdout")
    a = ap.parse_args()
    sys.exit({"scan": cmd_scan, "check": cmd_check, "show": cmd_show, "callers": cmd_callers,
              "reconcile": cmd_reconcile, "render": cmd_render}[a.cmd](a) or 0)

if __name__ == "__main__":
    main()
